Base plugin version
JetBrains-Research/ideformer-plugin pull request #1
Opened 2023-08-24 23:12 UTC by diffitask

2023-10-17 08:47 UTC, nbirillo requested changes
I have not looked at the request bodies in the server and the module with the plugin in detail. If you have any questions, feel free to dm me.
Btw, great work!

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/README.md
> +Run `./runPluginStarter.sh <absolute path to the project> <server host> <server port>` command from the root of the project.
I'd also suggest creating [an idea run configuration](https://www.jetbrains.com/help/idea/run-debug-configuration.html) to be able to run the project from ij IDEA directly

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/build.gradle.kts
> +group = "org.jetbrains.research.IdeAssistantPlugin"
You can put 
```kotlin
group = rootProject.group
version = rootProject.version
```

Into `build.gradle.kts` in all submodules, to be able to publish the plugin easier

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/api/PsiElementsUtils.kt
> +object PsiElementsUtils {
In kotlin it is not necessary to wrap util functions into an object, I'd suggest to move the `findSubdirectory` function to the top-level

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/api/PsiElementsUtils.kt
> +object PsiElementsUtils {
I'd suggest to change this function into an extension one, it looks prettier, what do you think?
```kotlin
fun PsiDirectory.findSubdirectory(targetDirectoryPath: String): PsiDirectory? {...}
```

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/api/PsiElementsUtils.kt
> +object PsiElementsUtils {
Also, it is better to rename findSubdirectory into findSubdirectoryRecursively to indicate that this function works recursively

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/api/IdeApi.kt
> +package org.jetbrains.research.ideFormerPlugin.api
I'd suggest to divide this file into several ones and also move to a nested folder `models`

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/api/IdeApi.kt
> +package org.jetbrains.research.ideFormerPlugin.api
The proposed list of files:
- `BaseMethods.kt` with `IdeApiMethod` and `ReversibleApiMethod`
- a separate file for each class

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/api/IdeApi.kt
> +    fun getExecutionRes(): String
I'd suggest to rename into `executionResult`. It is usually best to avoid such abbreviations in method names

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/api/IdeApi.kt
> +interface ReversibleApiMethod {
Should it be in some relation with `IdeApiMethod`? I mean `ReversibleApiMethod : IdeApiMethod`

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/api/IdeApi.kt
> +class GetProjectModules(private val project: Project) : IdeApiMethod {
You use Get in these two names - GetProjectModules and GetKtFileKtMethods and don't use it for the ListDirectoryContents class. Probably it is better to unify naming and add get everywhere or delete it everywhere

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/api/IdeApi.kt
> +    private lateinit var projectModules: List<Module>
Instead of using lateinit I'd recommend to init the list with an empty list or with null. The same comment is true for all classes here

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/api/IdeApi.kt
> +        fun getProjectModules(project: Project): List<Module> =
I'd suggest to rewrite: `private fun Project.modules() = ModuleManager.getInstance(this).modules.toList()`

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/api/IdeApi.kt
> +    private val curDirectory: PsiDirectory,
What is the current directory? Project directory? For me it is a little bit unclear what this name means

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/api/IdeApi.kt
> +            ?: throw Exception("No such file in the current directory")
It's a bad practice to throw such a general Exception, in this case probably it's enough to use error("...")

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/api/IdeApi.kt
> +        fun getKtFileKtMethods(ktFile: KtFile): List<KtNamedFunction> =
The same - private fun KtFile.ktNamedFunctions() =  PsiTreeUtil.findChildrenOfType(this, KtNamedFunction::class.java).toList()

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/api/IdeApi.kt
> +        fileKtMethods = getKtFileKtMethods(ktFile)
```kotlin
getKtFileByName(ktFileName).also {
            fileKtMethods = getKtFileKtMethods(it)
        }
```

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/api/IdeApi.kt
> +    internal fun getMethodsNames() = fileKtMethods.map { it.name }
Why do you need this function? You can directly use it:
`override fun getExecutionRes(): String = fileKtMethods.map { it.name }.toString()`

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/api/IdeApi.kt
> +    private val dirName: String = "."
I'd suggest to add `private const val DEFAULT_DIR_NAME = "."` into the companion object and use it here

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/api/IdeApi.kt
> +    private lateinit var dirContents: List<PsiFileSystemItem>
Hm, PsiFileSystemItem is not content directly, maybe should you rename it?

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/api/IdeApi.kt
> +        fun getListDirectoryContents(psiDirectory: PsiDirectory): List<PsiFileSystemItem> {
`fun PsiDirectory.directoryContent() ...`

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/api/IdeApi.kt
> +            "." -> curDirectory
DEFAULT_DIR_NAME -> curDirectory

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/api/IdeApi.kt
> +    internal fun getDirContentsNames() = dirContents.map { it.name }
The same, you don't need this extra function

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/api/IdeApi.kt
> +    private val targetDirName: String = "."
The same, you can move into a const, since you use the same const several times you can move it into utils

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/api/IdeApi.kt
> +            ?: throw Exception("No such directory in a project: '$targetDirName'.")
error("...")

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-core/src/test/kotlin/org/jetbrains/research/ideFormerPlugin/api/IdeApiTest.kt
> +package org.jetbrains.research.ideFormerPlugin.api
I'd suggest to add GitHub Actions to the repo to check tests remotely also

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/stateKeeper/IdeStateKeeper.kt
> +    }
I'd suggest to replace with
```kotlin
    var curDirectory: PsiDirectory = findCurrentDirectory()

    // TODO: to think about null project path processing
    private fun findCurrentDirectory() = userProject.guessProjectDir()?.let { projectBaseDir ->
        ApplicationManager.getApplication().runReadAction<PsiDirectory> {
            PsiManager.getInstance(userProject).findDirectory(projectBaseDir)
        }
    } ?: error("No project file path")
```

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/stateKeeper/IdeStateKeeper.kt
> +    fun saveReversibleApiCall(apiCall: ReversibleApiMethod) = apiCallStack.addElement(apiCall)
I'd suggest use the same terminology everywhere - you have ReversibleApiMethod, but this function has the name `saveReversibleApiCall `. It would be great to use method or call everywhere

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/stateKeeper/IdeStateKeeper.kt
> +}
You can rewrite it
```kotlin
        repeat(apiCallsCount) {
            if (apiCallStack.empty()) {
                return it + 1 // if you need to return e.g. 1, not zero, I am not sure here, but according to the old code it should be 1
            }

            apiCallStack.pop().reverse()
        }
        return apiCallsCount
```

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-core/src/test/kotlin/org/jetbrains/research/ideFormerPlugin/api/IdeApiTest.kt
> +    }
You can cut it and delete the same code fragments:
```kotlin
    fun testListDirectoryContents() {
        val ideStateKeeper = IdeStateKeeper(project)

        mapOf(
            // TODO: Use a const with default name here instead of "." 
            "." to setOf("dir1", "dir2"),
            "dir1" to setOf("someKtFile2.kt",  "subdir"),
            "dir2/subdir/subsubdir" to setOf("someTextFile.txt")
        ).forEach { (dirName, expectedResult) ->
            ListDirectoryContents(ideStateKeeper.curDirectory, dirName).also {
                it.execute()
                assertEquals(expectedResult, it.getDirContentsNames().toSet())
            }
        }
        // TODO: to add test for a non-existing dir
    }
```

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-core/src/test/kotlin/org/jetbrains/research/ideFormerPlugin/api/IdeApiTest.kt
> +    }
You can rewrote all other tests in the same way

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/build.gradle.kts
> +    id("io.ktor.plugin") version "2.3.3"
I'd suggest to use a toml file for versions, it is more convenient for multi-module projects

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-server/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/server/IdeServer.kt
> +    private lateinit var ideStateKeeper: IdeStateKeeper
Why do you need it as a class field? you can create it inside the startServer function, since you need a new instance per project

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-server/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/server/IdeServer.kt
> +data class ServerAnswer(val serverAnswer: String)
Since you have only one field, probably it is better to use an [inline](https://kotlinlang.org/docs/inline-classes.html) class

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-server/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/server/IdeServer.kt
> +data class ServerAnswer(val serverAnswer: String)
Answer -> Response

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-server/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/server/IdeServer.kt
> +package org.jetbrains.research.ideFormerPlugin.server
I'd suggest to divide this file into several ones:
- IdeServer.kt + the module function here
- IdeServerService.kt
- Models.kt with ServerAnswer class
- Routing.kt - move constants to this file and also put the configureRouting function there, just call the route functions
- requests/... several files for different types of routing implementation here here

if you have any questions, please ask in dm

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-server/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/server/IdeServer.kt
> +    routing {
It will be like 
```kotlin
routing {
     getMainPage()
    .....
}
```

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-server/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/server/IdeServer.kt
> +        get("/") {
You can rewrite with 
```kotlin
fun Routing. getMainPage() {
     get("/") {....}
}
```

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-server/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/server/IdeServer.kt
> +                IdeServer::class.java.classLoader.getResourceAsStream("ideApiDescriptions/ideApiDescriptions.json")!!
Where is it should be? I don't see this file in the resources

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-server/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/server/IdeServer.kt
> +                IdeServer::class.java.classLoader.getResourceAsStream("ideApiDescriptions/ideApiDescriptions.json")!!
I found it in another module, usually, resources are stored in the same module where they are used. Also, it is better to store them at the same path as the class, e.g. if the IdeServer class is stored in org.jetbrains.research.ideFormerPlugin.server, the resources for this class should be stored in the same package, but in the resources folder, in this case you can use "IdeServer::class.java.getResource("ideApiDescriptions.json")"

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/ide-server-starter/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/IdeServerStarter.kt
> +        val projectOpener = ProjectOpener(null, null)
Are you sure about two nulls, in this case the project will not be resolved

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/plugin/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/IdeAssistantToolWindowFactory.kt
> +            userProject.service<IdeServerService>().startServer()
You have to put port and host here, in other cases this code is incorrect

2023-10-17 08:47 UTC, nbirillo commented on ide-former-plugin/plugin/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/IdeAssistantToolWindowFactory.kt
> +                    chatArea.append("User: $userQuery\n")
It is better to use `System.lineSeparator()`

2023-10-23 12:38 UTC, diffitask commented on ide-former-plugin/plugin/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/IdeAssistantToolWindowFactory.kt
> +            userProject.service<IdeServerService>().startServer()
Since we haven't thought out enough the mechanism of interaction between the plugin and the server, so far I've set default parameters in the startServer method, so the server is started on user localhost

2023-10-25 11:52 UTC, diffitask commented on ide-former-plugin/ide-server-starter/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/IdeServerStarter.kt
> +        val projectOpener = ProjectOpener(null, null)
Thank you for paying my attention to this) I will add project resolving when it is necessary for our scenarios

2023-10-25 12:14 UTC, diffitask commented on ide-former-plugin/ide-core/src/test/kotlin/org/jetbrains/research/ideFormerPlugin/api/IdeApiTest.kt
> +    }
I corrected testListDirectory test case, as you showed👍 In the other two tests, different api methods are used + they need to be saved as variables so that reverse() can be called on them later, so such a nice option with the map won't work here:/ (I've left the previous code for now)

2023-10-25 12:31 UTC, diffitask commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/api/IdeApi.kt
> +    private lateinit var projectModules: List<Module>
Lateinit is used in IDE API classes' fields that store execution result, so if a method that returns execution result description is called before execute() was called, the uninitialized property exception will be thrown. Based on these thoughts, I would like to keep lateinit, what do you think about it?

2023-10-25 15:05 UTC, diffitask commented on ide-former-plugin/ide-core/src/test/kotlin/org/jetbrains/research/ideFormerPlugin/api/IdeApiTest.kt
> +package org.jetbrains.research.ideFormerPlugin.api
I'll add it a bit later)

2023-10-30 08:49 UTC, nbirillo commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/api/IdeApi.kt
> +    private lateinit var projectModules: List<Module>
Yep, it is the reason why I asked to change it. This part is the worst design solution in Kotlin.
I mean you can use something like this:

```kotlin
class ProjectModules(private val project: Project) : IdeApiMethod {
    private var projectModules: List<Module>? = null
    private fun Project.modules(): List<Module> = ModuleManager.getInstance(this).modules.toList()

    override fun execute() {
        projectModules = project.modules()
    }

    fun getProjectModulesNames(): List<String>? = projectModules?.map { it.name }?.toList()
}
```

in this case you _will not_ get the uninitialized property exception, since the property is always initialized. Otherwise, you _will_ probably catch this exception if you call `getProjectModulesNames` earlier than `execute`. It is just a safer way to work with the response in your case
Yep, you have to handle `null` cases, but this extra work just indicates that something went wrong and the `execute` method was not handled for some reason. We can discuss it in more detail in dm if you wish

2023-10-30 08:59 UTC, nbirillo commented on ide-former-plugin/ide-core/src/test/kotlin/org/jetbrains/research/ideFormerPlugin/api/IdeApiTest.kt
> +    }
You still can make tests better, e.g. for `testChangeDirectory`:
```kotlin
    // TODO: rename
    private fun changeDirectoryTestCase(
        ideStateKeeper: IdeStateKeeper,
        targetDirName: String,
        expected: String = targetDirName
    ) = ChangeDirectory(ideStateKeeper, targetDirName).also {
        it.execute()
        assertEquals(expected, ideStateKeeper.currentProjectDirectory.name)
    }

    fun testChangeDirectory() {
        val ideStateKeeper = IdeStateKeeper(project)

        val cdSubDir = changeDirectoryTestCase(ideStateKeeper, "dir1")
        val cdSecondChanging = changeDirectoryTestCase(ideStateKeeper, "subdir")

        cdSecondChanging.reverse()
        assertEquals("dir1", ideStateKeeper.currentProjectDirectory.name)

        // second reverse does nothing
        cdSecondChanging.reverse()
        assertEquals("dir1", ideStateKeeper.currentProjectDirectory.name)

        cdSubDir.reverse()
        assertEquals("src", ideStateKeeper.currentProjectDirectory.name)

        changeDirectoryTestCase(ideStateKeeper, "dir2/subdir/subsubdir", "subsubdir")

        // TODO: to add test for a non-existing dir
    }
```

2023-10-30 09:05 UTC, nbirillo commented on ide-former-plugin/ide-core/src/test/kotlin/org/jetbrains/research/ideFormerPlugin/api/IdeApiTest.kt
> +    }
for `testKtFileKtMethods`:
```kotlin
    private fun changeDirectoryAndGetKtMethodsTestCase(
        ideStateKeeper: IdeStateKeeper,
        targetDirName: String,
        ktFileName: String,
        expectedMethods: Set<String>
    ) {
        val cd = ChangeDirectory(ideStateKeeper, targetDirName)
        cd.execute()

        val ktFileMethods = KtFileKtMethods(ideStateKeeper.currentProjectDirectory, ktFileName)
        ktFileMethods.execute()
        assertEquals(expectedMethods, ktFileMethods.getFileKtMethodsNames().toSet())
    }

    fun testKtFileKtMethods() {
        val ideStateKeeper = IdeStateKeeper(project)

        mapOf(
            Pair("dir1", "someKtFile2.kt") to setOf("decreaseNum", "printSomePhrase"),
            Pair("subdir", "someKtFile1.kt") to setOf("main", "increaseNum"),
        ).forEach { (dirToKtFile, expectedNames) ->
            val (dir, ktFile) = dirToKtFile
            changeDirectoryAndGetKtMethodsTestCase(
                ideStateKeeper,
                dir, ktFile, expectedNames
            )
        }
    }
```

2023-10-30 09:22 UTC, nbirillo requested changes
I left some comments about testing and lateinit and also some thoughts about possible improvements, but you have already done a great job! code looks awesome!

2023-10-30 09:22 UTC, nbirillo commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/api/models/KtFileKtMethods.kt
> +    private lateinit var fileKtMethods: List<KtNamedFunction>
I already left a comment about this

2023-10-30 09:22 UTC, nbirillo commented on ide-former-plugin/ide-server/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/server/Routing.kt
> +val jsonConverter = Gson()
It is not a good idea to have a global not constant variable

2023-10-30 09:22 UTC, nbirillo commented on ide-former-plugin/ide-server/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/server/requests/getChangeDirectory.kt
> +        }
It is not necessary to change, just one of the possible ways:
```kotlin
        val changeDirectory = targetDirName?.let {
            ChangeDirectory(ideStateKeeper, targetDirName)
        } ?: ChangeDirectory(ideStateKeeper)
```

2023-10-30 09:22 UTC, nbirillo commented on ide-former-plugin/ide-server/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/server/requests/getListDirectoryContents.kt
> +        }
I guess you can also move this function outside like `executeAndCatchError` and reuse it everywhere to avoid code duplication

2023-10-30 16:29 UTC, nbirillo approved these changes
It looks awesome!

2023-10-30 18:11 UTC, merged