Python projects support, new file related APIs
JetBrains-Research/ideformer-plugin pull request #2
Opened 2023-11-02 19:39 UTC by diffitask

2023-11-10 13:11 UTC, tiginamaria requested changes
All is great, thank you a lot for your work! I've left just a few small comments, clarifications and advise

2023-11-10 13:11 UTC, tiginamaria commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/api/models/fileRelated/fileClasses/JavaFileClasses.kt
> +
I totally understand, why you can not make this method generic, but maybe you can move some common parts to utils `PsiElementsUtils.kt` like following

```
inline fun <reified T : PsiElement> getPsiElementsOfType(projectDirectory: PsiDirectory, fileName: String): List<T> {
    val psiFile = projectDirectory.findFileByName(fileName)
    return psiFile.psiElementsOfType<T>()
}
```
 and use in inside`execute`

2023-11-10 13:11 UTC, tiginamaria commented on ide-former-plugin/ide-server/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/server/requests/fileRelated/getFileClasses.kt
> +    get("/file-classes/{fileName?}") {
Why `fileName` marked as optional parameter in this request? If there is some insight reason, please leave a comment

2023-11-10 13:11 UTC, tiginamaria commented on ide-former-plugin/ide-server/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/server/requests/fileRelated/getFileFunctions.kt
> +    get("/file-functions/{fileName?}") {
Same

2023-11-10 13:11 UTC, tiginamaria commented on ide-former-plugin/ide-server/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/server/requests/fileRelated/getFileText.kt
> +    get("/file-text/{fileName?}") {
Same

2023-11-10 13:11 UTC, tiginamaria commented on ide-former-plugin/ide-core/src/test/kotlin/org/jetbrains/research/ideFormerPlugin/api/models/fileRelated/FileFunctionsTest.kt
> +        checkFileMethodsExecution(
It would be better to use parametrized tests, but it's your choice. If it's easier as this for now, it's ok

2023-11-10 13:11 UTC, tiginamaria commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/api/models/utils/ApiUtils.kt
> +        "kt" -> KtFileClasses(projectDirectory, fileName)
Maybe add enums for file extensions?

2023-11-10 16:41 UTC, diffitask commented on ide-former-plugin/ide-core/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/api/models/fileRelated/fileClasses/JavaFileClasses.kt
> +
Thank you for this idea of refactoring! Code looks better now! I spent a lot of time trying to bring all these classes to a single view (tried generic abstract class FileClasses/Functions and etc)🙈 but all attempts failed due to the lack of a common ancestor, closer than PsiElement, or because of the inability to make execute() generic (can’t get a class of a type T inside it due to its mark ‘override’)🫠

2023-11-10 17:05 UTC, diffitask commented on ide-former-plugin/ide-server/src/main/kotlin/org/jetbrains/research/ideFormerPlugin/server/requests/fileRelated/getFileClasses.kt
> +    get("/file-classes/{fileName?}") {
There is a reason to mark this parameter (and actually all required parameters) as optional. If the url for the ktor server would be written as ‘/file-classes/{fileName}’ (without a question mark the fileName parameter is required), this means that to call this get method we should write the required slash before the fileName parameter (e.g. ‘file-classes/RealClass.kt’). In the case of several parameters, all the required parameters will first have to be passed through a slash, and in the end the optional parameters will be called through a question (e.g. ‘file-classes/RealClass.kt/someAnotherReq/…?someOptionalReq=…). 

Forcing a model to follow such a complex rule when composing a url can be problematic. It’s much easier to tell it to write all the parameters for calling this method through a question mark and '&' marks.

We give our model, which accesses to the server, the knowledge that this parameter is actually required (described in [ideApiDescriptions.json](https://github.com/JetBrains-Research/ideformer-plugin/blob/main/ide-former-plugin/ide-server/src/main/resources/org/jetbrains/research/ideFormerPlugin/server/ideApiDescriptions.json)). And if the model hasn’t set the value of this parameter, it will get the text error about it anyway

2023-11-14 07:59 UTC, diffitask commented on ide-former-plugin/ide-core/src/test/kotlin/org/jetbrains/research/ideFormerPlugin/api/models/fileRelated/FileFunctionsTest.kt
> +        checkFileMethodsExecution(
Thank you for the idea, I'll try to figure it out later)

2023-11-14 14:41 UTC, tiginamaria approved these changes
All looks great! Thank you =)

2023-11-14 14:44 UTC, merged